### ISSUE TITLE
Can not switch language in vim.

### ISSUE THREAD

**Issue by wsdjeg** [k-takata/vim-win32-installer#2]
hi @k-takata @chrisbra 
  I am using https://github.com/vim/vim-win32-installer, but I can not change the message language of vim to english. 
  I have language messages en_US.UTF-8 in my vimrc, and gui menu is english, but when I run `:message`, I still see chinese, it should be english too.
  due to this issue, I can not use vim-signify. see [this issue](https://github.com/mhinz/vim-signify/issues/187)
  wsdjeg
  thanks!

**Comment by chrisbra** [comment]
submitted upstream: vim/vim#1082

Will track there.

**Comment by wsdjeg** [comment]
@chrisbra thanks

**Comment by k-takata** [comment]
This is not a problem of installer itself. Closing.
