### ISSUE TITLE
Vim 64bit installer in windows10 will be smartscreen but 32bit will not

### ISSUE THREAD

**Issue by fhopecc** [k-takata/vim-win32-installer#6]
Vim 64bit installer in windows10 will be smartscreen but 32bit will not be screened. 
In that computer in my company, I should install vim32bit and python 32bit. Why 64bit be screened.?

**Comment by k-takata** [comment]
The algorithms of SmartScreen are not open. So, we cannot know the reasons.
The warning should be mostly a false positive. If you think it is safe, you may ignore the warning.
